### ISSUE TITLE
Print function name in error in `verbose-vm-error`

### ISSUE THREAD

**Issue by XVilka** [yuriy-chumak/ol#10]
When there is arity error - it prints something like:
```
ERROR: src/olvm.c/2034
error:  function #<function> got did not want 0 arguments 
```
I found that the code printing this error is in `lang/primop.scm` in function `verbose-vm-error`.
Is there any way to print also function name?

**Comment by yuriy-chumak** [comment]
Yes, the way exists.
This is already planned, but a bit later.

I can explain more if it really important.

**Comment by XVilka** [comment]
yep, if you can point me where I can read that information about failing function - adding this feature wont (shouldn't) be a problem.

**Comment by yuriy-chumak** [comment]
Well. You can't get the function name of arity error easily.

First of all, "src/olvm.c/2034" is ARITY error - means that some lambda called with unexpected arguments count.

Ol is compiler (in the OLVM code, but into code and with losing the intermediate text data). In opposite to the symbols, functions can have same body for different names (if they compiled into same code) - this is job of (fork-bytecode-interner) function in lang/assemble.scm - so interpreter must have some additional debug data to identify what function is failed.

I have planned this job, and it will be done as part of big rework of error printing mech very shortly. But for now it has less priority than pinvoke (that require better docs and structured table of type conversions) and resource consumption issues.

p.s. As temporary solution I can propose only the step-by-step programming with manual controlling the count of lambda arguments, sorry.
