### ISSUE TITLE
Option to set "root" dir for scheme files

### ISSUE THREAD

**Issue by XVilka** [yuriy-chumak/ol#14]
To be able to set root directory - not only current one for `(import (...))` declarations.

**Comment by yuriy-chumak** [comment]
The second default path for loading libraries is "/usr/lib/ol" for linux and "C:\Program Files\OL" for windows.

For OL you can change it using environment variable OL_HOME (buggy, fix will at very soon), or using `(define *include-dirs* (cons "/my/lib/directory" *include-dirs*))` at the script beginning.

**Comment by yuriy-chumak** [comment]
Fixed. Now OL_HOME works as expected.
