### ISSUE TITLE
Option to compile bytecode from command line

### ISSUE THREAD

**Issue by XVilka** [yuriy-chumak/ol#15]
To be able call something like `ol -o example.bl example.scm`

**Comment by yuriy-chumak** [comment]
I have removed this functionality from ol.
You can use next code for compilation (assume that "main" is main function for your "example.scm" source code):
```
echo "$(cat example.scm) (write-bytes stdout (fasl-encode main))" |ol >example.bl
```

**Comment by XVilka** [comment]
Well, I can understand why you did remove that functionality from ol itself. But may be providing some additional small utility which will do this is a way to go?
