### ISSUE TITLE
Prompt is not displayed.

### ISSUE THREAD

**Issue by SaitoAtsushi** [yuriy-chumak/ol#37]
Otus Lisp do not print prompt on [mintty](https://mintty.github.io/) of [MSYS2](http://www.msys2.org/).

`_isatty` return zero always about `stdin` and `stdout` on pseudo terminal of Cygwin and Msys, because standard input and output will be connected with mintty via pipe. (pipe is not tty.)

A known workaround is to check pipe name.
Please see [Vim](https://github.com/vim/vim/blob/792f0e36593d1ec13ccb8a622ca5542c500577b4/src/iscygpty.c#L107-L168) for an example.

But this workaround is dirty hack and solves only  case of mintty.
There is cases that another pseudo terminal may not named pipe.

I think that a command line option for to change to interactive mode should be added.
Human's judgement is better rather than way do not exist.

**Comment by yuriy-chumak** [comment]
Hello, Saito

There are already two command line switches - "--interactive" and "--no-interactive" that controls the ol prompt. In addition, you can define global symbol "*interactive*" as #true to enable the prompt during REPL session.

You can check [the code](https://github.com/yuriy-chumak/ol/blob/baeae2623fef26a3adb999865777a0d840548381/src/ol.scm#L274).

With respect,
YC.

_Sorry for late answer. I had a long and nice vacation without any civilization (and internet, sure)._

**Comment by SaitoAtsushi** [comment]
Thanks for your reply.

I tried that, it report error message.

![ol](https://user-images.githubusercontent.com/299440/67265489-d08cf700-f4e8-11e9-91e2-353256585f14.png)

I don't know the cause at current, this message doesn't seem to be in the ol's source code.
The problem may be specific to my environment.

If there is a cause in ol, I'll report it in a new issue.

**Comment by yuriy-chumak** [comment]
Let's try "ol - --interactive". For historical reasons first ol parameter always should be a file ("-" for stdin) and not an option.

But You force me to think about changing command line format and make it more usual... Thank you for the issue!

**Comment by SaitoAtsushi** [comment]
Thank you!

That is what I needed.

**Comment by yuriy-chumak** [comment]
I updated command line. Please, use "ol --interactive" instead of "ol - --interactive" for newer ol versions.
