### ISSUE TITLE
TODO - Build for Raspian on the Raspberry Pi 3 and 4

### ISSUE THREAD

**Issue by staypufd** [yuriy-chumak/ol#39]
I would love to see a build for Raspian OS on the Raspberry Pi 3 and 4 models.  Just discovered this today, so hope I'm not missing it, but if not it would be neat to have.

**Comment by yuriy-chumak** [comment]
Hello, staypufd.

I'm checked the build under qemu and it works.

![image](https://user-images.githubusercontent.com/2684656/88436817-cbf5c600-ce0d-11ea-9f5a-eff7aee6dabd.png)

Can you recheck and notify me about any issues?

**Comment by yuriy-chumak** [comment]
Well, I've tested again and closing the issue.
