### ISSUE TITLE
wasm REPL is unusable after one mistake

### ISSUE THREAD

**Issue by mjobuda** [yuriy-chumak/ol#44]
If you make one error in the REPL you cannot use it anymore and have to reload the page.
![image](https://user-images.githubusercontent.com/14003621/133696079-859cad2d-85b7-4783-a2e2-e4c31c24bf8e.png)

**Comment by yuriy-chumak** [comment]
Thank you very much.

Online ol version updated from 2.2 to 2.2.1 (build 2941).
Issue fixed.
![Снимок экрана от 2021-09-27 18-43-24](https://user-images.githubusercontent.com/2684656/134941362-4158e560-2783-443d-ac6d-a7af9d56f3f1.png)

Will be very thankful if you can confirm the fix.

**Comment by mjobuda** [comment]
Confirmed, seems to work now. You are welcome, yuriy. Kiss, kiss, functional lisps will rule the world!

**Comment by yuriy-chumak** [comment]
Thanks!
Closed.
