### ISSUE TITLE
Please add build dependency `xxd`

### ISSUE THREAD

**Issue by glyh** [yuriy-chumak/ol#49]
When building, I found this command missing.

**Comment by yuriy-chumak** [comment]
Yes, `xxd` is required to integrate repl binary into c code. The `xxd` is a part of `vim`.

Thank you. I added dependency to the project [README](https://github.com/yuriy-chumak/ol#build--install).

**Comment by yuriy-chumak** [comment]
Additional instructions available at the [BUILD page](https://github.com/yuriy-chumak/ol/blob/master/doc/BUILD.md).

**Comment by glyh** [comment]
Great, closing up.
