### ISSUE TITLE
Owl-Lisp c-code generator

### ISSUE THREAD

**Issue by nullscm** [yuriy-chumak/ol#56]
Is it possible to include something like this in otus?

Owl-Lisp can generate c-code with it's binary ol -o hello.c hello.scm.

Though not really cross-platform because it's relying on POSIX.

Would be really cool if otus could do the same with it's more powerful libraries and really platform independence (mostly) :)

**Comment by yuriy-chumak** [comment]
Yes, it's possible.
Unfortunately, I don't have such plans in near feature. I don't see any real benefits in c-code generation worth to make a lisp code wider.

But! I have a plan to add a [JIT](https://en.wikipedia.org/wiki/Just-in-time_compilation). This will (yes!) give a real speedup and will be done as part of Olvm, not as part of Ol.
