### ISSUE TITLE
Cannot import `(scheme srfi-170)`

### ISSUE THREAD

**Issue by bentxt** [yuriy-chumak/ol#60]
In a gitter thread in Jan 19 2023

> [SRFI-170](https://srfi.schemers.org/srfi-170/srfi-170.html) is partially implemented. I mean [file and folder functions](https://github.com/yuriy-chumak/ol/blob/master/libraries/scheme/srfi-170.scm). I'm freezing at this point because a lot of tests are required.
 
Unfortunately I cannot import this 
```
./ol
(import (scheme srfi-170))
Import failed because (scheme srfi-170) could not be found.
```

The import works for other srfis.

**Comment by yuriy-chumak** [comment]
That's strange...
```bash
~/Workspace/ol.git$ sudo make uninstall
rm -rf /usr/bin/ol
rm -rf /usr/bin/olvm
rm -rf /usr/lib/libol.so
rm -rf /usr/lib/ol/repl
rm -rf /usr/lib/ol
rm -rf /usr/include/ol
rm -rf /usr/share/man/man1/ol.1.gz

~/Workspace/ol.git$ sudo make install
# install Ol executable(s) to /usr/bin:
Installing main binary...
install -d /usr/bin
install ol /usr/bin/ol
Installing ol virtual machine binary...
install -d /usr/bin
install vm /usr/bin/olvm
Installing libol.so...
install libol.so /usr/lib/libol.so
Installing headers...
install -d /usr/include/ol
install -m 644 includes/ol/vm.h /usr/include/ol/vm.h
install -m 644 includes/ol/ol.h /usr/include/ol/ol.h
# and libraries to /usr/lib/ol:
Installing basic libraries...
cd libraries && find * -type d -exec install -d "{}" "/usr/lib/ol/{}" \;
cd libraries && find * -type f -exec install -m 644 "{}" "/usr/lib/ol/{}" \;
# install Ol binary REPL to /usr/lib/ol:
Installing REPL...
install -d /usr/lib/ol
install -m 644 repl /usr/lib/ol/repl
Installing man page...
install -d /usr/share/man/man1
gzip <ol.1 >/usr/share/man/man1/ol.1.gz
Ok.

~/Workspace/ol.git$ ./ol
Welcome to Otus Lisp 2.3.9-3574-5707caf6
type ',help' to help, ',quit' to end session.
> (import (scheme srfi-170))
> ;; Library (scheme srfi-170) added
> ;; Imported (scheme srfi-170)
> 
```

I'll recheck with fresh new VM.

**Comment by yuriy-chumak** [comment]
It works under fresh new VM without any changes.

@bentxt, try to `make uninstall; make install`.
OR
`./ol --home=`pwd`/libraries` in the Ol repository to test.

**Comment by lassik** [comment]
In Scheme we generally use `(import (srfi 170))`. RnRS reserves the `(import (scheme <...>))` library namespace for itself. What's the rationale for diverging from this convention?

**Comment by yuriy-chumak** [comment]
> What's the rationale

Historical reasons.
I haven't seen any srfi location standard, but you'r right I think... Hmmmm.

**Comment by yuriy-chumak** [comment]
* guile: `(srfi srfi-1)`
* chez: no srfi (?)
* chibi: `(srfi 1)`
* chicken: `srfi-1`
* gambit: `(srfi 1)`
* gauche: `(srfi 1)`
* kawa: `(srfi :101)`
* mit: `(runtime srfi-1)`
* racket: `srfi/1`
* stklos: `(srfi 1)`

Which one is better? ))

**Comment by lassik** [comment]
It's kind of obscure, but [R7RS section 5.6.1 _Library Syntax_](https://standards.scheme.org/corrected-r7rs/r7rs-Z-H-7.html#TAG:__tex2page_sec_5.6.1) says:

> Libraries whose first identifier is `scheme` are reserved for use by this report and future versions of this report. Libraries whose first identifier is `srfi` are reserved for libraries implementing Scheme Requests for Implementation.

This is the `(srfi 1)` form that all R7RS implementations now use. (Guile was the last holdout, but `(import (srfi 1))` now works in Guile 3.0.9.)

**Comment by lassik** [comment]
* In a recent MIT Scheme, try `,(import (srfi 1))` with the comma. It should work.
* In Chicken, try `chicken-install r7rs && csi -R r7rs` and `(import (srfi 1))`.
* Chez (and many other R6RS implementations) can use [`chez-srfi`](https://github.com/arcfide/chez-srfi). The syntax then is `(import (srfi :1))`. The is `:` a hack due to a limitation in the R6RS standard that library name parts cannot be numbers.

**Comment by yuriy-chumak** [comment]
> Libraries whose first identifier is `srfi` are reserved for libraries implementing Scheme Requests for Implementation.

Ah, I see!

Thank you. I'll update provided Ol's srfi implementations according to R<sup>7</sup>RS.

**Comment by lassik** [comment]
Excellent. Thank you very much!

**Comment by yuriy-chumak** [comment]
`(import (scheme srfi-170))` works fine.
`(import (srfi 170))` works fine.

Closing.
Feel free to open new one if needed.
![image](https://user-images.githubusercontent.com/2684656/217887618-e009908a-9d12-4726-925c-83bf77a91a3a.png)
