### ISSUE TITLE
Installation fails with custom prefix because $PREFIX/lib is assumed to be pre-existing

### ISSUE THREAD

**Issue by avatarwin** [yuriy-chumak/ol#61]
The build process should probably use `install -d` for the library

**Comment by yuriy-chumak** [comment]
Yes, it does. Something wrong with installation? Can you provide more info?

Part of makefile with "install -d":
![image](https://user-images.githubusercontent.com/2684656/218334920-41eca304-7c2b-42e9-9c44-e2bffc7ba9bd.png)

**Comment by avatarwin** [comment]
Yes, but it fails on line 16 before the part where $PREFIX/lib is created

**Comment by yuriy-chumak** [comment]
Yeah, you right. Fixed. 513fda61e1f606747f55439be45908e135a6353b

Thank you!
