### ISSUE TITLE
Please update embedding section in README

### ISSUE THREAD

**Issue by XVilka** [yuriy-chumak/ol#8]
To match the current situation.

**Comment by yuriy-chumak** [comment]
In progress. Latest updates can be found in "develop" branch.

**Comment by yuriy-chumak** [comment]
More info added in embed sample - [sample.c](https://github.com/yuriy-chumak/ol/blob/master/extensions/embed/sample.c). Readme will be updated soon.

**Comment by yuriy-chumak** [comment]
Looks like finished.
36cc378bc0ed7d6da3179aeb157c3606071325b4
